# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
default_install_hook_types: [pre-commit, commit-msg, pre-push]
default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        exclude: package-lock.json
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.16.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        args: [ --rev-range, origin/main..HEAD ]
        stages: [push]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
    - id: markdownlint-fix
      args: [--fix, --disable=MD013, --disable=MD029 ]
    - id: markdownlint
      args: [ --disable=MD013,--disable=MD029 ]

  - repo: local
    hooks:
      - id: vue-cli-service-lint
        name: vue-cli-service-lint
        entry: npm run lint
        files: "^src"
        pass_filenames: false
        types_or: [javascript]
        language: node
