name: Publish

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main]

env:
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  docker-build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login with registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.IMAGE_REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag
            type=raw,value=latest
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: mode=max
          sbom: true
          push: true
