name: Test

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build

  lint:
    name: Lint repository files
    runs-on: ubuntu-latest
    needs: [build]
    env:
      SKIP: "gitleaks"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  scan:
    name: Scan git history
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install scan dependencies
        run: pip install commitizen
      - name: Run Commitizen
        run: python -m commitizen check --rev-range origin/upstream..HEAD
      - name: Run GitLeaks
        run: docker run -v $(pwd):/repo ghcr.io/gitleaks/gitleaks:latest detect --verbose --source="/repo"

  docker-build:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [lint, scan]
    if: ${{ github.event_name != 'push' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
